<div id="floater" style="display: none;">
    <a href="javascript:void(0)" onclick="javascript:esconde()" class="bt-fecharbanner">Clique aqui para fechar</a>	
    <div class="aviso">
        <div class="avatar"><?php echo $this->wp_config_notice['teste']; ?></div>
        <span class="ident"><strong><?php echo $this->wp_config_notice['teste'] ? $this->wp_config_notice['teste'] : ''; ?></strong></span>
        <span class="ident" style="margin-top:3px"><strong><?php echo $this->wp_config_notice['teste'] ? $this->wp_config_notice['teste'] : ''; ?></strong></span>
        <div class="content">
            <p>Olá, <strong><?php echo $this->wp_config_notice['teste']; ?></strong><br />
            <?php echo $this->wp_config_notice['teste']; ?>
            </p>
            <p> Seu acesso será bloqueado em <?php echo $this->wp_config_notice['teste'] ?> dias.<br />			
                Data do bloqueio <em><strong><?php echo $this->wp_config_notice['teste'] ?></em></strong><br /><br />
                Lembre-se de manter em dia nossa parceria.
            </p>

            <p>Caso já tenha efetuado o pagamento, favor desconsidere este aviso</p>
            <div class="ass">
                Email:<?php echo$this->wp_config_notice['teste'] ?><br />
                Fone:<?php echo $this->wp_config_notice['teste'] ? $this->wp_config_notice['teste'] : ''; ?>
            </div>
        </div>	
    </div>
</div>